### ISSUE TITLE
Sale contract should ensure it has all tokens 

### ISSUE THREAD

**Issue by ethers** [AdChain/token-launch-contracts#4]
Related to #3

In the Sale constructor, all tokens should allocated to the Sale
https://github.com/AdChain/tokenlaunch/blob/397dad15713039817afd539112fe918eddbd7578/contracts/Sale.sol#L31
like:
```
token = StandardToken(_token);
token.transfer(this, token.totalSupply());
if (token.balanceOf(this) != token.totalSupply()) throw;
if (token.balanceOf(this) != 10**6) throw;
```
Included additional checks for safety, minimal gas cost and only done once since in constructor.

**Comment by skmgoldin** [comment]
Addressed in https://github.com/AdChain/token-launch-contracts/commit/347db2d5f5af84ba1e312641a3b237f53cb43f8f

Will close when merged to master.
