### ISSUE TITLE
wallet can purchase tokens

### ISSUE THREAD

**Issue by ethers** [AdChain/token-launch-contracts#8]
The team (via `wallet`) needs to be trusted that it won't purchase tokens themselves while the sale is happening.  As the sale is happening, there is no code that prevents the `wallet` from calling `purchaseTokens` using the ETH it is simultaneously raising.

Although this behavior can be detected by the public, this behavior can be prevented in code by using something like:
https://github.com/status-im/status-network-token/blob/master/contracts/ContributionWallet.sol

Something to consider.

**Comment by flyingdutchie** [comment]
i did send 50 eth and all the verifications where done but still now tokens in my wallet what do i do wrong?????
